name: Docker CD

on:
  workflow_run:
    workflows: CI
    types:
      - completed
  
jobs:
  build_and_publish:
    runs-on: self-hosted
    steps:
      # - uses: actions/checkout@v3
      # - name: get container status
      #   run: |
      #     if docker ps | grep -q "posting-service"; then
      #       echo "Container is already running"
            
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username coen-donk --password ${{ secrets.POSTING_SERVICE_SECRET }} ghcr.io
          docker build ./. --tag ghcr.io/coen-donk/posting-service:latest
          docker push ghcr.io/coen-donk/posting-service:latest
          docker build ./. -tag ghcr.io/coen-donk/gateway:latest
          docker push ./. ghcr.io/coen-donk/gateway:latest
          docker stop posting-service
          docker remove posting-service
          docker stop gateway
          docker remove gateway
          
          docker run -d --name posting-service -p 8080:80 --network proxynetwork ghcr.io/coen-donk/posting-service:latest
          docker run -d --name gateway -p 5001:80 --network proxynetwork ghcr.io/coen-donk/gateway:latest
          
          
